seed: 42
total_timesteps: 300000
output: "results/trainingv3n17e073"
visualize: true
n_eval_episodes: 10
# algorithmic components
defaults:
  - map: n17e073
  - gym: ScalarFieldEnv62
  - robot: Uni4D
  - benchmark: poamn17e073
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_


